### PR TITLE
Feature/tags

### PR DESCRIPTION
**Pull request by BrianTipton1**
Added ability to specify specific TMX tags when randomly getting maps. Any questions/concerns let me know

### CODE REVIEW

**Comment by XertroV** [comment]
At first glance, looks great! Thanks!

Will test it out and it'll be in the next release assuming no major issues. I might tweak a few things, too.

**Comment by XertroV** [comment]
@BrianTipton1 how would you like to be credited btw? I'm not sure what you go by in the TM world (or what name you'd prefer, in general). You can ping me via the openplanet discord (or other TM discords) via `@XertroV#1337`

**Comment by XertroV** [comment]
Oh btw, you can see the tweaks I made here: https://github.com/XertroV/tm-better-room-manager/commit/6eb9e71a26953dcf76338b3db48b0cc258d03f88

Mostly adding handles, adding proper defaults (so that if someone chooses all tags, they really do get all tags), and some style/safety stuff (I didn't notice any issues with your code, but it's refactored slightly to fit more with my code-style-preference). There are also a few other lines changed independent of your code.

**Comment by XertroV** [comment]
FYI @BrianTipton1 I've added you as `BrianTipton1` in the authors in the readme + the changelog on openplanet. LMK if you'd prefer another name and I'll update both.

**Comment by BrianTipton1** [comment]
@XertroV Perfect, thanks for merging and adding me to the README.

**Pull request merged**
